-- 增量开启 pgvector，并为现有 artworks 表补充 512 维图像向量字段
create extension if not exists vector with schema extensions;

alter table public.artworks
add column if not exists image_embedding extensions.vector(512);

comment on column public.artworks.image_embedding is
'CLIP image embedding generated by Xenova/clip-vit-base-patch32 for visual search.';

create index if not exists artworks_image_embedding_hnsw_idx
on public.artworks
using hnsw (image_embedding extensions.vector_cosine_ops);

create or replace function public.match_artworks_by_image(
  query_embedding extensions.vector(512),
  match_threshold double precision default 0.2,
  match_count integer default 5
)
returns table (
  id text,
  title text,
  title_zh text,
  category text,
  category_zh text,
  period text,
  period_zh text,
  image text,
  gallery_images jsonb,
  description text,
  description_zh text,
  listing_type text,
  feature_vector jsonb,
  image_signature jsonb,
  case_record jsonb,
  uploaded_by uuid,
  is_official boolean,
  is_for_sale boolean,
  price numeric,
  currency text,
  collection_id text,
  similarity double precision
)
language sql
stable
as $$
  select
    a.id,
    a.title,
    a.title_zh,
    a.category,
    a.category_zh,
    a.period,
    a.period_zh,
    a.image,
    a.gallery_images,
    a.description,
    a.description_zh,
    a.listing_type,
    a.feature_vector,
    a.image_signature,
    a.case_record,
    a.uploaded_by,
    a.is_official,
    a.is_for_sale,
    a.price,
    a.currency,
    a.collection_id,
    greatest(0, 1 - (a.image_embedding <=> query_embedding)) as similarity
  from public.artworks a
  where a.image_embedding is not null
    and greatest(0, 1 - (a.image_embedding <=> query_embedding)) >= match_threshold
  order by a.image_embedding <=> query_embedding
  limit least(greatest(match_count, 1), 5);
$$;

grant execute on function public.match_artworks_by_image(
  extensions.vector(512),
  double precision,
  integer
) to anon, authenticated, service_role;
