import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case chinese = "zh-Hans"

    var id: String { rawValue }

    var locale: Locale {
        Locale(identifier: rawValue)
    }
}

final class LanguageManager: ObservableObject {
    @Published var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: Self.storageKey)
        }
    }

    static let storageKey = "eastwood.language"

    init() {
        if let saved = UserDefaults.standard.string(forKey: Self.storageKey),
           let language = AppLanguage(rawValue: saved) {
            self.language = language
        } else if let preferred = Locale.preferredLanguages.first, preferred.hasPrefix("zh") {
            self.language = .chinese
        } else {
            self.language = .english
        }
    }

    func text(_ key: String) -> String {
        switch language {
        case .english:
            return Self.english[key] ?? key
        case .chinese:
            return Self.chinese[key] ?? Self.english[key] ?? key
        }
    }

    func format(_ key: String, _ args: CVarArg...) -> String {
        String(format: text(key), locale: language.locale, arguments: args)
    }

    private static let english: [String: String] = [
        "tab.home": "Home",
        "tab.collections": "Display",
        "tab.shop": "Shop",
        "tab.cases": "Cases",
        "tab.more": "More",
        "nav.eastwood": "Eastwood",
        "nav.collections": "Collection Display",
        "nav.shop": "Antique Shop",
        "nav.cases": "Return Cases",
        "nav.more": "More",
        "alert.sessionExpired.title": "Session expired",
        "alert.sessionExpired.message": "Please sign in again.",
        "common.brand": "Eastwood Auction",
        "common.ok": "OK",
        "common.retry": "Retry",
        "common.cancel": "Cancel",
        "common.delete": "Delete",
        "common.done": "Done",
        "common.save": "Save",
        "common.close": "Close",
        "error.invalidURL": "Invalid URL",
        "error.unauthorized": "Unauthorized",
        "error.network": "Network error",
        "error.timeout": "Request timed out. Please try again.",
        "error.offline": "No network connection. Please check your internet.",
        "error.server": "Server error. Please try again later.",
        "error.authentication": "Authentication failed. Please sign in again.",
        "error.imageInvalid": "Invalid image",
        "error.imageSearchFailed": "Image search failed.",
        "error.configMissing": "App configuration is missing.",
        "error.signInFailed": "Sign in failed. Please check your email and password.",
        "common.search": "Search",
        "common.email": "Email",
        "common.password": "Password",
        "common.phone": "Phone",
        "home.featured": "FEATURED",
        "home.hero.subtitle": "Curated Chinese antiques with premium collector workflows.",
        "home.pill.curated": "Curated",
        "home.pill.cloud": "Cloud",
        "home.pill.native": "Native",
        "home.latestHighlights": "Latest Highlights",
        "home.artworks": "Artworks",
        "home.shop": "Shop",
        "home.cases": "Cases",
        "state.unableToLoad": "Unable to Load",
        "more.title": "More",
        "more.subtitle": "Tools, account access, and content modules in one place.",
        "more.mainTools": "Main Tools",
        "more.contentModules": "Content Modules",
        "more.preferences": "Preferences",
        "more.language": "Language",
        "more.language.subtitle": "Switch between English and Chinese instantly.",
        "more.imageSearch": "Image Search",
        "more.imageSearch.subtitle": "Find similar antiques from a photo",
        "more.profile": "Profile",
        "more.profile.subtitle": "Account, inbox, and cloud data",
        "more.exhibitions": "Auctions",
        "more.exhibitions.subtitle": "Featured auction items and preview highlights",
        "more.visit": "Browse",
        "more.visit.subtitle": "Browse catalog items and send inquiries",
        "more.support": "Services",
        "more.support.subtitle": "Collector, consignor, and buyer support",
        "more.donation": "Consignment",
        "more.donation.subtitle": "Submit antiques for review and cataloging",
        "language.english": "English",
        "language.chinese": "Chinese",
        "profile.title": "Profile",
        "profile.subtitle": "Account access, saved items, and cloud messages.",
        "profile.account": "Account",
        "profile.loggedIn": "Logged in",
        "profile.signOut": "Sign out",
        "profile.cloudData": "Cloud Data",
        "profile.mySaved": "My Saved",
        "profile.mySaved.subtitle": "Favorites saved to the cloud",
        "profile.inquiries": "Consign & Inquire",
        "profile.inquiries.subtitle": "Send a consignment or item inquiry",
        "profile.inbox": "Inbox",
        "profile.inbox.subtitle": "Messages, replies, and processing updates",
        "profile.admin": "Admin Panel",
        "profile.adminArtworks": "Catalog Management",
        "profile.adminArtworks.subtitle": "Manage catalog items and listing states",
        "profile.adminInquiries": "Inquiry Center",
        "profile.adminInquiries.subtitle": "Review consignment and inquiry workflows",
        "profile.adminUsers": "User Management",
        "profile.adminUsers.subtitle": "Manage account roles and permissions",
        "saved.signInRequired": "Sign In Required",
        "saved.signInRequired.message": "Please sign in to view cloud favorites.",
        "saved.empty": "No Favorites Yet",
        "saved.empty.message": "Save artworks to build your personal shortlist.",
        "login.signIn": "Sign in",
        "search.title": "Search",
        "search.prompt": "Search antiques, categories, or periods",
        "section.collections": "Collection Display",
        "section.shop": "Antique Shop",
        "section.cases": "Return Cases",
        "section.activeListings": "Active Listings",
        "section.curatedList": "Curated List",
        "section.searchIn": "Search in %@",
        "section.sort": "Sort",
        "section.sort.newest": "Newest",
        "section.sort.titleAZ": "Title A-Z",
        "section.display.list": "List",
        "section.display.cards": "Cards",
        "section.all": "All",
        "section.category": "Category",
        "section.period": "Period",
        "section.forSale": "For Sale",
        "section.hero.shop": "Browse live sale items with quick filters and clean list browsing.",
        "section.hero.default": "Discover carefully selected pieces with native filtering and smooth browsing.",
        "imageSearch.title": "Image Search",
        "imageSearch.visualSearch": "Visual Search",
        "imageSearch.subtitle": "Search for antiques by photo and find the closest matching catalog items.",
        "imageSearch.scopeTitle": "How Matching Works",
        "imageSearch.scopeBody": "Customer image matching prioritizes public sale products. Display-only collection pieces stay searchable in the admin knowledge base and return cases remain part of the archive.",
        "imageSearch.tipTitle": "Recommended Upload",
        "imageSearch.tipBody": "Use a clear front-facing item photo. JPG, PNG, or WebP works best for similarity search and admin review.",
        "imageSearch.selectImage": "Select an image to search",
        "imageSearch.chooseImage": "Choose Image",
        "imageSearch.threshold": "Match Threshold: %@",
        "imageSearch.resultCount": "Result Count: %@",
        "imageSearch.noMatches": "No matches found",
        "imageSearch.noMatches.message": "Try lowering threshold or selecting a clearer image.",
        "imageSearch.effectiveThreshold": "Effective threshold: %@",
        "imageSearch.returnedResults": "Returned results: %@",
        "imageSearch.cloudUploaded": "Cloud query image uploaded",
        "imageSearch.analysis": "Image Analysis",
        "imageSearch.snapshotNote": "Knowledge base counts include sale products, display collection items, and archived return cases synced from Supabase.",
        "imageSearch.knowledge": "Knowledge Base",
        "imageSearch.totalItems": "Total Items",
        "imageSearch.productItems": "Products for Sale",
        "imageSearch.collectionItems": "Display Collection",
        "imageSearch.caseRecords": "Return Cases",
        "imageSearch.match": "Match",
        "imageSearch.brightness": "Brightness",
        "imageSearch.contrast": "Contrast",
        "imageSearch.sharpness": "Sharpness",
        "imageSearch.recommend.blur": "Photo appears blurry. Move closer and keep the camera steady for better matches.",
        "imageSearch.recommend.contrast": "Photo contrast is low. Improve lighting or avoid strong glare.",
        "imageSearch.recommend.dark": "Image is dark. Increase lighting or exposure for stronger matching.",
        "imageSearch.recommend.good": "Image quality looks good for visual matching.",
        "artwork.official": "Official",
        "artwork.user": "User",
        "artwork.community": "Community",
        "artwork.product": "Product for Sale",
        "artwork.collection": "Display Collection",
        "artwork.returnCase": "Return Case",
        "artwork.case": "Case",
        "artwork.forSale": "For Sale",
        "artwork.notForSale": "Not For Sale",
        "artwork.view": "View",
        "artwork.id": "ID",
        "inquiry.title": "Consign & Inquire",
        "inquiry.pageDescription": "Send a consignment or item inquiry to Eastwood Auction. Logged-in personal users can leave the item code, request details, and contact information for our team.",
        "inquiry.signInRequired": "Sign In Required",
        "inquiry.signInRequired.message": "Please sign in before submitting a consignment or inquiry.",
        "inquiry.personalUsersOnly": "Personal Users Only",
        "inquiry.personalUsersOnly.message": "Administrator accounts should handle consignments and inquiries from the inbox or admin modules.",
        "inquiry.noCode": "No item code",
        "inquiry.code": "Item Code",
        "inquiry.code.placeholder": "Enter item code",
        "inquiry.phone.placeholder": "Enter phone number",
        "inquiry.email.placeholder": "Enter email",
        "inquiry.details": "Details",
        "inquiry.details.placeholder": "Tell us what you want to ask, consign, or confirm in detail.",
        "inquiry.submitted": "Submitted",
        "inquiry.submitFailed": "Submit failed",
        "inquiry.submit": "Submit Consignment / Inquiry",
        "content.exhibitions.title": "Auctions",
        "content.exhibitions.subtitle": "Featured auction items and online preview highlights from Eastwood Auction.",
        "content.exhibitions.special": "Featured Auction Items",
        "content.exhibitions.onSite.title": "On-site Highlights",
        "content.exhibitions.onSite.desc": "Explore rotating curation themes and specialist-led showcase selections.",
        "content.exhibitions.online.title": "Online Viewing",
        "content.exhibitions.online.desc": "Browse selected catalog lots and exhibition previews online.",
        "content.exhibitions.featuredWorks": "Featured Works",
        "content.exhibitions.browseMore": "Browse More",
        "content.exhibitions.eventFeed.title": "Event Feed",
        "content.exhibitions.eventFeed.desc": "Exhibition cards and featured lots are updated from cloud inventory.",
        "content.exhibitions.collectorSupport.title": "Collector Support",
        "content.exhibitions.collectorSupport.desc": "Create an account to save items and track inquiry progress.",
        "content.quickActions": "Quick Actions",
        "content.openShop": "Open Antique Shop",
        "content.openCollections": "Open Collections",
        "content.visit.title": "Browse",
        "content.visit.subtitle": "Plan your consultation and auction viewing experience.",
        "content.visit.before": "Before You Inquire",
        "content.visit.appointment.title": "Appointment Recommended",
        "content.visit.appointment.desc": "Send an inquiry in advance to confirm item availability, condition, and pricing.",
        "content.visit.preparation.title": "Preparation",
        "content.visit.preparation.desc": "Bring provenance photos, invoices, and condition notes for faster review.",
        "content.visit.imageSearch.title": "Image Search",
        "content.visit.imageSearch.desc": "Use image search first if you want to find similar antiques from catalog.",
        "content.visit.onSite": "Client Support",
        "content.visit.consultation.title": "Consultation",
        "content.visit.consultation.desc": "Specialists provide valuation references and consignment suggestions.",
        "content.visit.consignment.title": "Consignment Guidance",
        "content.visit.consignment.desc": "We explain listing strategy, reserve pricing, and risk notes clearly.",
        "content.visit.policy.title": "Policy Notes",
        "content.visit.policy.desc": "Shipping, pickup, and payment details are finalized after inquiry confirmation.",
        "content.openInquiries": "Open Consignment & Inquiry",
        "content.openImageSearch": "Open Image Search",
        "content.support.title": "Services",
        "content.support.subtitle": "Browse, consign, inquire, and purchase with confidence.",
        "content.support.serviceAreas": "Service Areas",
        "content.support.collector.title": "Collector Account",
        "content.support.collector.desc": "Create an account to save favorites and follow inquiry updates.",
        "content.support.consign.title": "Consign",
        "content.support.consign.desc": "Submit antique items for review and let our team prepare buyer-facing presentation.",
        "content.support.shop.title": "Shop Antiques",
        "content.support.shop.desc": "Browse available antiques, decorative objects, and collectible works online.",
        "content.support.workflow": "Inquiry Workflow",
        "content.support.statusSync.title": "Status Sync",
        "content.support.statusSync.desc": "Pending -> Processed -> Archived states remain synced with cloud status.",
        "content.support.inboxTracking.title": "Inbox Tracking",
        "content.support.inboxTracking.desc": "View replies, unread updates, and historical messages in one thread.",
        "content.openInbox": "Open Inbox",
        "content.submitInquiry": "Submit Consignment / Inquiry",
        "content.donation.title": "Consignment",
        "content.donation.subtitle": "Consign with Eastwood Auction and bring antiques to market.",
        "content.donation.path": "Consignment Path",
        "content.donation.cataloging.title": "Cataloging",
        "content.donation.cataloging.desc": "We assist with cataloging, presentation, and buyer matching.",
        "content.donation.appraisal.title": "Appraisal Request",
        "content.donation.appraisal.desc": "Share item details and photos for preliminary evaluation.",
        "content.donation.prepare": "What to Prepare",
        "content.donation.itemInfo.title": "Item Information",
        "content.donation.itemInfo.desc": "Provide item background, condition notes, and provenance records when available.",
        "content.donation.communication.title": "Communication",
        "content.donation.communication.desc": "Our team follows up in inbox to confirm next steps.",
        "content.startConsignment": "Start a Consignment",
        "content.openCases": "Open Return Cases",
        "inbox.title": "Inbox",
        "inbox.pageDescription": "See the consignment and inquiry messages you have already sent, along with their current processing status.",
        "inbox.adminDescription": "Review all consignment and inquiry messages in one inbox view, reply to customers here, and manage processing status.",
        "inbox.signInFirst": "Please sign in first",
        "inbox.pending": "Pending",
        "inbox.processed": "Processed",
        "inbox.archived": "Archived",
        "inbox.unread": "Unread: %@",
        "inbox.retry": "Retry",
        "inbox.emptyTitle": "No messages yet",
        "inbox.empty": "No consignment or inquiry messages in this state",
        "inbox.noCodeInquiry": "No Item Code",
        "inbox.inquiry": "Inquiry",
        "inbox.markProcessed": "Mark Processed",
        "inbox.archive": "Archive",
        "inbox.restore": "Restore",
        "inbox.tapAgain": "Tap Again",
        "inbox.reply": "Reply...",
        "inbox.send": "Send",
        "inbox.readOnly": "Archived records are read-only.",
        "inbox.conversation": "Conversation",
        "inbox.details": "Details",
        "inbox.submittedAt": "Submitted",
        "inbox.contactPhone": "Phone",
        "inbox.contactEmail": "Email",
        "inbox.replyBoxAdmin": "Reply to this customer",
        "inbox.replyBoxUser": "Continue this conversation",
        "detail.title": "Detail",
        "detail.platformUpload": "Platform Upload",
        "detail.personalUpload": "Personal Upload",
        "detail.status": "Status",
        "detail.type": "Type",
        "detail.price": "Price",
        "detail.archive": "Archive",
        "detail.availability": "Availability",
        "detail.saleState": "Sale State",
        "detail.listingType": "Listing Type",
        "detail.collectionId": "Collection ID",
        "detail.category": "Category",
        "detail.period": "Period",
        "detail.itemInfo": "Item Info",
        "detail.source": "Source",
        "detail.inquiryCode": "Item Code",
        "detail.uploaderEmail": "Uploader Email",
        "detail.uploaderId": "Uploader ID",
        "detail.askAbout": "Ask About This Item",
        "detail.manageItem": "Manage This Item",
        "detail.nextSteps": "Next Steps",
        "detail.gallery": "Gallery",
        "detail.gallerySubtitle": "Review all photos synced with the web detail page and the admin catalog.",
        "detail.galleryCount": "%d photos",
        "detail.galleryCounter": "%d / %d",
        "detail.caseDetails": "Case Details",
        "detail.caseId": "Case ID",
        "detail.salePrice": "Sale Price",
        "detail.saleTime": "Sale Time",
        "detail.salePlatform": "Sale Platform",
        "detail.clientRegion": "Client Region",
        "detail.logisticsCost": "Logistics Cost",
        "detail.purchaseChannel": "Purchase Channel",
        "detail.purchaseCost": "Purchase Cost",
        "detail.riskAdvice": "Risk Advice",
        "detail.description": "Description",
        "admin.accessRequired": "Admin Access Required",
        "admin.inquiries.title": "Inquiry Center",
        "admin.inquiries.center": "Inquiry Center",
        "admin.inquiries.subtitle": "Review and process consignments and inquiries with cloud-synced status.",
        "admin.inquiries.stats": "Pending %@ · Processed %@ · Archived %@",
        "admin.filter": "Filter",
        "admin.searchInquiries": "Search code, details, phone, or email",
        "admin.noCode": "No Code",
        "admin.noCode.all": "No Code: All",
        "admin.noCode.only": "Only No Code",
        "admin.noCode.withCode": "Only With Code",
        "admin.unread": "Unread",
        "admin.unread.all": "Unread: All",
        "admin.unread.only": "Only Unread",
        "admin.unread.read": "Only Read",
        "admin.select": "Select",
        "admin.done": "Done",
        "admin.exportCsv": "Export CSV",
        "admin.retry": "Retry",
        "admin.inquiries.empty": "No consignments or inquiries in this state",
        "admin.noCodeInquiry": "No Code",
        "admin.view": "View",
        "admin.process": "Process",
        "admin.archive": "Archive",
        "admin.restore": "Restore",
        "admin.processSelected": "Process Selected",
        "admin.archiveSelected": "Archive Selected",
        "admin.tapAgain": "Tap Again",
        "admin.inquiryDetail": "Inquiry Detail",
        "admin.close": "Close",
        "admin.inquirySection": "Inquiry",
        "admin.detailsSection": "Details",
        "admin.actionsSection": "Actions",
        "admin.messagesSection": "Messages",
        "admin.code": "Code",
        "admin.phone": "Phone",
        "admin.email": "Email",
        "admin.created": "Created",
        "admin.replyToUser": "Reply to user...",
        "admin.replyFailed": "Reply failed.",
        "admin.statusUpdateFailed": "Status update failed.",
        "admin.noMessages": "No messages",
        "admin.send": "Send",
        "admin.users.title": "User Management",
        "admin.users.header": "User Management",
        "admin.users.subtitle": "Manage account roles and moderation actions.",
        "admin.users.admins": "Administrators",
        "admin.users.users": "Users",
        "admin.users.none": "No users",
        "admin.users.noneAdmins": "No admin users",
        "admin.users.noEmail": "No email",
        "admin.users.admin": "Admin",
        "admin.users.user": "User",
        "admin.users.setUser": "Set User",
        "admin.users.setAdmin": "Set Admin",
        "admin.users.delete": "Delete",
        "admin.users.confirmTap": "Tap again to confirm",
        "admin.users.unnamed": "Unnamed user",
        "admin.users.deleteTitle": "Delete user?",
        "admin.delete.message": "This action cannot be undone.",
        "admin.artworks.title": "Catalog Management",
        "admin.artworks.header": "Artwork Console",
        "admin.artworks.subtitle": "Manage catalog items, pricing, and listing states.",
        "admin.artworks.search": "Search catalog items",
        "admin.artworks.type": "Type",
        "admin.artworks.all": "All",
        "admin.artworks.product": "Product for Sale",
        "admin.artworks.collection": "Display Collection",
        "admin.artworks.case": "Return Case",
        "admin.artworks.sale": "Sale",
        "admin.artworks.saleAll": "Sale: All",
        "admin.artworks.forSale": "For Sale",
        "admin.artworks.notForSale": "Not For Sale",
        "admin.artworks.price": "Price",
        "admin.artworks.priceAll": "Price: All",
        "admin.artworks.priceUnder1k": "< 1,000",
        "admin.artworks.price1kTo5k": "1,000-5,000",
        "admin.artworks.priceAbove5k": "> 5,000",
        "admin.artworks.caseAll": "Case: All",
        "admin.artworks.hasCase": "Has Case",
        "admin.artworks.noCase": "No Case",
        "admin.artworks.none": "No artworks found for current filter.",
        "admin.artworks.collectionId": "Collection ID",
        "admin.artworks.uploader": "Uploader",
        "admin.artworks.deleteSelected": "Delete Selected (%@)",
        "admin.artworks.exportSubject": "Catalog Export",
        "admin.artworks.exportMessage": "Filtered artworks CSV",
        "admin.artworks.create": "Create Artwork",
        "admin.artworks.edit": "Edit Artwork",
        "admin.artworks.imported": "Imported %@ / %@",
        "admin.artworks.unknownError": "Unknown error",
        "admin.artworks.deleteTitle": "Delete artwork?",
        "admin.artworks.deleteSelectedTitle": "Delete selected artworks?",
        "admin.artworks.count": "%@ artworks",
        "admin.artworks.official": "Official",
        "admin.artworks.user": "User",
        "admin.artworks.deleteMessage": "This action cannot be undone.",
        "admin.importReport": "Import Report",
        "admin.summary": "Summary",
        "admin.imported": "Imported",
        "admin.failed": "Failed",
        "admin.failureDetails": "Failure Details",
        "admin.importSuccess": "All rows imported successfully.",
        "admin.batchImport": "Batch Import",
        "admin.inputFormat": "Input Format",
        "admin.inputFormat.desc": "One line per artwork: title|imageUrl|description|price(optional)|collectionId(optional)|currency(optional)|titleZh(optional)|categoryZh(optional)|periodZh(optional)|descriptionZh(optional)|caseId(optional)|salePrice(optional)|saleTime(optional)|salePlatform(optional)|clientRegion(optional)|logisticsCost(optional)|purchaseChannel(optional)|purchaseCost(optional)|riskAdvice(optional)",
        "admin.exampleLine": "Example line...",
        "admin.sharedFields": "Shared Fields",
        "admin.listingType": "Listing Type",
        "admin.category": "Category",
        "admin.period": "Period",
        "admin.validation": "Validation",
        "admin.validRows": "Valid rows: %@",
        "admin.importValidOnly": "Import valid rows only (skip invalid)",
        "admin.import": "Import",
        "admin.basic": "Basic",
        "admin.title": "Title",
        "admin.titleZh": "Title (Chinese)",
        "admin.categoryZh": "Category (Chinese)",
        "admin.periodZh": "Period (Chinese)",
        "admin.coverUrl": "Cover Image URL",
        "admin.description": "Description",
        "admin.descriptionZh": "Description (Chinese)",
        "admin.uploadCover": "Upload Cover",
        "admin.listing": "Listing",
        "admin.priceField": "Price",
        "admin.currency": "Currency",
        "admin.collectionIdField": "Collection ID",
        "admin.autoCollectionId": "Auto Generate Collection ID",
        "admin.galleryUrls": "Gallery URLs (one per line)",
        "admin.uploadGallery": "Upload Gallery Images",
        "admin.caseRecord": "Case Record (optional)",
        "admin.caseId": "Case ID",
        "admin.salePrice": "Sale Price",
        "admin.saleTime": "Sale Time",
        "admin.salePlatform": "Sale Platform",
        "admin.clientRegion": "Client Region",
        "admin.logisticsCost": "Logistics Cost",
        "admin.purchaseChannel": "Purchase Channel",
        "admin.purchaseCost": "Purchase Cost",
        "admin.riskAdvice": "Risk Advice",
        "admin.uploadingImages": "Uploading images...",
        "admin.save": "Save",
        "admin.validation.titleRequired": "Title is required.",
        "admin.validation.categoryRequired": "Category is required.",
        "admin.validation.periodRequired": "Period is required.",
        "admin.validation.coverUrlInvalid": "Cover image must be a valid URL.",
        "admin.validation.descriptionRequired": "Description is required.",
        "admin.validation.collectionRequired": "Collection listing requires Collection ID.",
        "admin.validation.collectionFormat": "Collection ID can use only a-z, 0-9, hyphen, underscore.",
        "admin.validation.collectionExists": "Collection ID already exists. Please use a unique value.",
        "admin.validation.pricePositive": "Price must be a positive number when item is for sale.",
        "admin.validation.caseSalePrice": "Case record requires Sale Price.",
        "admin.validation.caseSaleTime": "Case record requires Sale Time.",
        "admin.validation.caseSalePlatform": "Case record requires Sale Platform.",
        "admin.validation.galleryUrlInvalid": "All gallery image entries must be valid URLs.",
        "admin.error.loadArtworks": "Failed to load artworks",
        "admin.error.invalidBaseUrl": "Invalid app base URL.",
        "admin.error.invalidServerResponse": "Invalid server response.",
        "admin.error.unauthorized": "Unauthorized.",
        "admin.error.requestFailed": "Request failed: %@",
        "admin.error.invalidImage": "Invalid image",
        "admin.error.uploadFailed": "Upload failed",
        "admin.import.lineFormat": "Line %@: expected title|imageUrl|description + optional fields.",
        "admin.import.duplicateCollection": "Line %@: duplicate Collection ID in import batch.",
        "admin.import.invalidCurrency": "Line %@: currency must be USD or CNY.",
        "admin.deleteUserResult": "User deleted",
        "admin.roleUpdated": "Role updated"
    ]

    private static let chinese: [String: String] = [
        "tab.home": "首页",
        "tab.collections": "展示",
        "tab.shop": "商店",
        "tab.cases": "案例",
        "tab.more": "更多",
        "nav.eastwood": "Eastwood",
        "nav.collections": "藏品展示",
        "nav.shop": "古董商店",
        "nav.cases": "回流案例",
        "nav.more": "更多",
        "alert.sessionExpired.title": "登录已过期",
        "alert.sessionExpired.message": "请重新登录。",
        "common.brand": "Eastwood Auction",
        "common.ok": "好的",
        "common.retry": "重试",
        "common.cancel": "取消",
        "common.delete": "删除",
        "common.done": "完成",
        "common.save": "保存",
        "common.close": "关闭",
        "error.invalidURL": "无效链接",
        "error.unauthorized": "未授权",
        "error.network": "网络异常",
        "error.timeout": "请求超时，请稍后重试。",
        "error.offline": "当前无网络连接，请检查网络。",
        "error.server": "服务器异常，请稍后再试。",
        "error.authentication": "身份验证失败，请重新登录。",
        "error.imageInvalid": "图片无效",
        "error.imageSearchFailed": "图片搜索失败。",
        "error.configMissing": "应用配置缺失。",
        "error.signInFailed": "登录失败，请检查邮箱和密码。",
        "common.search": "搜索",
        "common.email": "邮箱",
        "common.password": "密码",
        "common.phone": "电话",
        "home.featured": "精选",
        "home.hero.subtitle": "精选中国古董，配合高级藏家工作流。",
        "home.pill.curated": "精选",
        "home.pill.cloud": "云端",
        "home.pill.native": "原生",
        "home.latestHighlights": "最新推荐",
        "home.artworks": "藏品",
        "home.shop": "商店",
        "home.cases": "案例",
        "state.unableToLoad": "加载失败",
        "more.title": "更多",
        "more.subtitle": "工具、账号入口和内容模块都在这里。",
        "more.mainTools": "主要工具",
        "more.contentModules": "内容模块",
        "more.preferences": "偏好设置",
        "more.language": "语言",
        "more.language.subtitle": "可随时切换中英文。",
        "more.imageSearch": "图片搜索",
        "more.imageSearch.subtitle": "通过照片查找相似古董",
        "more.profile": "我的",
        "more.profile.subtitle": "账号、收件箱和云端数据",
        "more.exhibitions": "拍卖",
        "more.exhibitions.subtitle": "精选拍卖商品与预展亮点",
        "more.visit": "浏览",
        "more.visit.subtitle": "浏览目录商品并发送咨询",
        "more.support": "服务",
        "more.support.subtitle": "面向藏家、委托方和买家的服务",
        "more.donation": "委托拍卖",
        "more.donation.subtitle": "提交古董进行审核与编目",
        "language.english": "English",
        "language.chinese": "中文",
        "profile.title": "我的",
        "profile.subtitle": "账号访问、收藏内容和云端消息。",
        "profile.account": "账号",
        "profile.loggedIn": "已登录",
        "profile.signOut": "退出登录",
        "profile.cloudData": "云端数据",
        "profile.mySaved": "我的收藏",
        "profile.mySaved.subtitle": "已保存到云端的收藏",
        "profile.inquiries": "委托与咨询",
        "profile.inquiries.subtitle": "提交委托或商品咨询",
        "profile.inbox": "收件箱",
        "profile.inbox.subtitle": "消息回复与处理进度",
        "profile.admin": "管理后台",
        "profile.adminArtworks": "管理藏品",
        "profile.adminArtworks.subtitle": "管理全部藏品",
        "profile.adminInquiries": "问询中心",
        "profile.adminInquiries.subtitle": "处理委托与咨询流程",
        "profile.adminUsers": "管理用户",
        "profile.adminUsers.subtitle": "用户与角色管理",
        "saved.signInRequired": "需要登录",
        "saved.signInRequired.message": "请先登录后查看云端收藏。",
        "saved.empty": "还没有收藏",
        "saved.empty.message": "收藏藏品后，这里会形成你的个人清单。",
        "login.signIn": "登录",
        "search.title": "搜索",
        "search.prompt": "搜索古董、分类或年代",
        "section.collections": "藏品展示",
        "section.shop": "古董商店",
        "section.cases": "回流案例",
        "section.activeListings": "在售列表",
        "section.curatedList": "精选列表",
        "section.searchIn": "搜索%@",
        "section.sort": "排序",
        "section.sort.newest": "最新",
        "section.sort.titleAZ": "标题 A-Z",
        "section.display.list": "列表",
        "section.display.cards": "卡片",
        "section.all": "全部",
        "section.category": "分类",
        "section.period": "年代",
        "section.forSale": "在售",
        "section.hero.shop": "浏览在售古董，配合快速筛选和清爽列表体验。",
        "section.hero.default": "通过原生筛选和顺滑浏览，发现精心挑选的作品。",
        "imageSearch.title": "图片搜索",
        "imageSearch.visualSearch": "视觉搜索",
        "imageSearch.subtitle": "通过照片搜索古董，并找到目录中最接近的匹配商品。",
        "imageSearch.scopeTitle": "匹配方式",
        "imageSearch.scopeBody": "客户图片匹配会优先命中公开在售商品。仅展示的藏品会保留在管理知识库中，回流案例则继续归档展示。",
        "imageSearch.tipTitle": "推荐上传",
        "imageSearch.tipBody": "建议上传正面清晰的商品照片。JPG、PNG、WebP 都适合做相似度搜索和后台审核。",
        "imageSearch.selectImage": "选择图片后开始搜索",
        "imageSearch.chooseImage": "选择图片",
        "imageSearch.threshold": "匹配阈值：%@",
        "imageSearch.resultCount": "结果数量：%@",
        "imageSearch.noMatches": "未找到匹配结果",
        "imageSearch.noMatches.message": "可以尝试降低阈值，或换一张更清晰的图片。",
        "imageSearch.effectiveThreshold": "实际阈值：%@",
        "imageSearch.returnedResults": "返回结果数：%@",
        "imageSearch.cloudUploaded": "查询图片已上传到云端",
        "imageSearch.analysis": "图片分析",
        "imageSearch.snapshotNote": "知识库统计包含已同步到 Supabase 的在售商品、展示藏品和回流案例。",
        "imageSearch.knowledge": "知识库",
        "imageSearch.totalItems": "总条目",
        "imageSearch.productItems": "商品（可出售）",
        "imageSearch.collectionItems": "藏品（仅展示）",
        "imageSearch.caseRecords": "回流案例",
        "imageSearch.match": "匹配度",
        "imageSearch.brightness": "亮度",
        "imageSearch.contrast": "对比度",
        "imageSearch.sharpness": "清晰度",
        "imageSearch.recommend.blur": "图片有些模糊。请靠近一些并保持稳定，有助于提高匹配效果。",
        "imageSearch.recommend.contrast": "图片对比度较低。建议改善光线或避免强反光。",
        "imageSearch.recommend.dark": "图片偏暗。建议增加光线或曝光，提高匹配效果。",
        "imageSearch.recommend.good": "图片质量不错，适合进行视觉匹配。",
        "artwork.official": "官方",
        "artwork.user": "用户",
        "artwork.community": "社区",
        "artwork.product": "商品",
        "artwork.collection": "藏品",
        "artwork.returnCase": "回流案例",
        "artwork.case": "案例",
        "artwork.forSale": "在售",
        "artwork.notForSale": "非卖品",
        "artwork.view": "查看",
        "artwork.id": "编号",
        "inquiry.title": "委托与咨询",
        "inquiry.pageDescription": "向 Eastwood Auction 提交委托或商品咨询。登录后的个人用户可以填写商品编号、详细需求和联系方式，交由团队跟进。",
        "inquiry.signInRequired": "需要登录",
        "inquiry.signInRequired.message": "请先登录后再提交委托或咨询。",
        "inquiry.personalUsersOnly": "仅限个人用户",
        "inquiry.personalUsersOnly.message": "管理员账号请通过收件箱或后台模块处理委托和咨询。",
        "inquiry.noCode": "没有商品编号",
        "inquiry.code": "商品编号",
        "inquiry.code.placeholder": "请输入商品编号",
        "inquiry.phone.placeholder": "请输入电话号码",
        "inquiry.email.placeholder": "请输入邮箱",
        "inquiry.details": "详细内容",
        "inquiry.details.placeholder": "请详细说明你想咨询、委托或确认的内容。",
        "inquiry.submitted": "提交成功",
        "inquiry.submitFailed": "提交失败",
        "inquiry.submit": "提交委托/咨询",
        "content.exhibitions.title": "拍卖",
        "content.exhibitions.subtitle": "Eastwood Auction 的精选拍卖与线上预展亮点。",
        "content.exhibitions.special": "精选拍卖商品",
        "content.exhibitions.onSite.title": "线下亮点",
        "content.exhibitions.onSite.desc": "探索轮换策展主题与专家主导的展示精选。",
        "content.exhibitions.online.title": "线上预览",
        "content.exhibitions.online.desc": "在线浏览精选图录拍品与展览预告。",
        "content.exhibitions.featuredWorks": "精选作品",
        "content.exhibitions.browseMore": "继续浏览",
        "content.exhibitions.eventFeed.title": "活动动态",
        "content.exhibitions.eventFeed.desc": "展览卡片和精选拍品会根据云端库存持续更新。",
        "content.exhibitions.collectorSupport.title": "藏家支持",
        "content.exhibitions.collectorSupport.desc": "注册账号即可保存藏品并跟踪问询进度。",
        "content.quickActions": "快捷操作",
        "content.openShop": "打开古董商店",
        "content.openCollections": "打开藏品展示",
        "content.visit.title": "浏览",
        "content.visit.subtitle": "规划你的咨询与拍卖预览体验。",
        "content.visit.before": "咨询前准备",
        "content.visit.appointment.title": "建议预约",
        "content.visit.appointment.desc": "提前发送咨询以确认商品库存、品相和价格信息。",
        "content.visit.preparation.title": "准备材料",
        "content.visit.preparation.desc": "可携带来源照片、票据和品相说明，方便更快评估。",
        "content.visit.imageSearch.title": "图片搜索",
        "content.visit.imageSearch.desc": "如果想先找相似古董，建议先使用图片搜索。",
        "content.visit.onSite": "客户支持",
        "content.visit.consultation.title": "现场咨询",
        "content.visit.consultation.desc": "专家会提供估值参考与委托建议。",
        "content.visit.consignment.title": "委托指导",
        "content.visit.consignment.desc": "我们会清晰说明上架策略、保留价和风险提示。",
        "content.visit.policy.title": "流程说明",
        "content.visit.policy.desc": "运输、自提与付款细节会在问询确认后最终确定。",
        "content.openInquiries": "打开委托与咨询",
        "content.openImageSearch": "打开图片搜索",
        "content.support.title": "服务",
        "content.support.subtitle": "安心浏览、委托、咨询与购买。",
        "content.support.serviceAreas": "服务范围",
        "content.support.collector.title": "藏家账户",
        "content.support.collector.desc": "创建账户可保存收藏并跟进问询更新。",
        "content.support.consign.title": "委托",
        "content.support.consign.desc": "提交古董藏品进行审核，我们的团队会准备面向买家的展示内容。",
        "content.support.shop.title": "古董商店",
        "content.support.shop.desc": "在线浏览可购买的古董、装饰器物与收藏作品。",
        "content.support.workflow": "问询流程",
        "content.support.statusSync.title": "状态同步",
        "content.support.statusSync.desc": "待处理 -> 已处理 -> 已归档 状态会和云端保持同步。",
        "content.support.inboxTracking.title": "收件箱跟踪",
        "content.support.inboxTracking.desc": "在同一线程里查看回复、未读更新和历史消息。",
        "content.openInbox": "打开收件箱",
        "content.submitInquiry": "提交委托/咨询",
        "content.donation.title": "委托拍卖",
        "content.donation.subtitle": "通过 Eastwood Auction 委托，让古董进入市场。",
        "content.donation.path": "委托路径",
        "content.donation.cataloging.title": "编目",
        "content.donation.cataloging.desc": "我们协助完成编目、展示和买家匹配。",
        "content.donation.appraisal.title": "估值申请",
        "content.donation.appraisal.desc": "分享藏品细节和照片，获取初步评估。",
        "content.donation.prepare": "需要准备什么",
        "content.donation.itemInfo.title": "藏品信息",
        "content.donation.itemInfo.desc": "尽量提供藏品背景、品相说明和来源记录。",
        "content.donation.communication.title": "沟通方式",
        "content.donation.communication.desc": "我们的团队会在收件箱中继续跟进后续步骤。",
        "content.startConsignment": "开始委托",
        "content.openCases": "打开回流案例",
        "inbox.title": "收件箱",
        "inbox.pageDescription": "查看你已发送的委托和咨询消息，以及它们当前的处理状态。",
        "inbox.adminDescription": "在一个收件箱中查看全部委托和咨询消息，在这里回复客户，并管理处理状态。",
        "inbox.signInFirst": "请先登录",
        "inbox.pending": "待处理",
        "inbox.processed": "已处理",
        "inbox.archived": "已归档",
        "inbox.unread": "未读：%@",
        "inbox.retry": "重试",
        "inbox.emptyTitle": "还没有消息",
        "inbox.empty": "当前状态下还没有委托或咨询记录",
        "inbox.noCodeInquiry": "无商品编号",
        "inbox.inquiry": "咨询",
        "inbox.markProcessed": "标记已处理",
        "inbox.archive": "归档",
        "inbox.restore": "恢复",
        "inbox.tapAgain": "再次点击确认",
        "inbox.reply": "回复...",
        "inbox.send": "发送",
        "inbox.readOnly": "已归档记录为只读状态。",
        "inbox.conversation": "对话",
        "inbox.details": "详细信息",
        "inbox.submittedAt": "提交时间",
        "inbox.contactPhone": "联系电话",
        "inbox.contactEmail": "联系邮箱",
        "inbox.replyBoxAdmin": "回复这位客户",
        "inbox.replyBoxUser": "继续这段对话",
        "detail.title": "详情",
        "detail.platformUpload": "平台上传",
        "detail.personalUpload": "个人上传",
        "detail.status": "状态",
        "detail.type": "类型",
        "detail.price": "价格",
        "detail.archive": "归档",
        "detail.availability": "销售信息",
        "detail.saleState": "销售状态",
        "detail.listingType": "条目类型",
        "detail.collectionId": "商品编号",
        "detail.category": "分类",
        "detail.period": "时期",
        "detail.itemInfo": "藏品信息",
        "detail.source": "来源",
        "detail.inquiryCode": "商品编号",
        "detail.uploaderEmail": "上传者邮箱",
        "detail.uploaderId": "上传者 ID",
        "detail.askAbout": "咨询这件藏品",
        "detail.manageItem": "管理这条内容",
        "detail.nextSteps": "下一步",
        "detail.gallery": "图片画廊",
        "detail.gallerySubtitle": "这里会同步展示网页详情页和后台目录里使用的全部图片。",
        "detail.galleryCount": "%d 张图片",
        "detail.galleryCounter": "%d / %d",
        "detail.caseDetails": "案例详情",
        "detail.caseId": "案例编号",
        "detail.salePrice": "成交价格",
        "detail.saleTime": "成交时间",
        "detail.salePlatform": "成交平台",
        "detail.clientRegion": "客户地区",
        "detail.logisticsCost": "物流成本",
        "detail.purchaseChannel": "采购渠道",
        "detail.purchaseCost": "采购成本",
        "detail.riskAdvice": "风险建议",
        "detail.description": "描述",
        "admin.accessRequired": "需要管理员权限",
        "admin.inquiries.title": "问询中心",
        "admin.inquiries.center": "问询中心",
        "admin.inquiries.subtitle": "查看并处理与云端同步的委托与咨询。",
        "admin.inquiries.stats": "未处理 %@ · 已处理 %@ · 已归档 %@",
        "admin.filter": "筛选",
        "admin.searchInquiries": "搜索编号 / 内容 / 电话 / 邮箱",
        "admin.noCode": "无编号",
        "admin.noCode.all": "无编号：全部",
        "admin.noCode.only": "仅无编号",
        "admin.noCode.withCode": "仅有编号",
        "admin.unread": "未读",
        "admin.unread.all": "未读：全部",
        "admin.unread.only": "仅未读",
        "admin.unread.read": "仅已读",
        "admin.select": "选择",
        "admin.done": "完成",
        "admin.exportCsv": "导出 CSV",
        "admin.retry": "重试",
        "admin.inquiries.empty": "当前状态下没有委托或咨询",
        "admin.noCodeInquiry": "无编号",
        "admin.view": "查看",
        "admin.process": "处理",
        "admin.archive": "归档",
        "admin.restore": "恢复",
        "admin.processSelected": "批量处理",
        "admin.archiveSelected": "批量归档",
        "admin.tapAgain": "再次点击确认",
        "admin.inquiryDetail": "咨询详情",
        "admin.close": "关闭",
        "admin.inquirySection": "咨询信息",
        "admin.detailsSection": "详细内容",
        "admin.actionsSection": "操作",
        "admin.messagesSection": "消息记录",
        "admin.code": "编号",
        "admin.phone": "电话",
        "admin.email": "邮箱",
        "admin.created": "创建时间",
        "admin.replyToUser": "回复用户...",
        "admin.replyFailed": "回复失败。",
        "admin.statusUpdateFailed": "状态更新失败。",
        "admin.noMessages": "暂无消息",
        "admin.send": "发送",
        "admin.users.title": "用户管理",
        "admin.users.header": "用户管理",
        "admin.users.subtitle": "管理账户角色和审核操作。",
        "admin.users.admins": "管理员",
        "admin.users.users": "普通用户",
        "admin.users.none": "暂无用户",
        "admin.users.noneAdmins": "暂无管理员",
        "admin.users.noEmail": "无邮箱",
        "admin.users.admin": "管理员",
        "admin.users.user": "用户",
        "admin.users.setUser": "设为用户",
        "admin.users.setAdmin": "设为管理员",
        "admin.users.delete": "删除",
        "admin.users.confirmTap": "再次点击确认",
        "admin.users.unnamed": "未命名用户",
        "admin.users.deleteTitle": "删除用户？",
        "admin.delete.message": "此操作无法撤销。",
        "admin.artworks.title": "藏品管理",
        "admin.artworks.header": "藏品控制台",
        "admin.artworks.subtitle": "管理目录藏品、价格和上架状态。",
        "admin.artworks.search": "搜索目录商品",
        "admin.artworks.type": "类型",
        "admin.artworks.all": "全部",
        "admin.artworks.product": "商品",
        "admin.artworks.collection": "藏品",
        "admin.artworks.case": "案例",
        "admin.artworks.sale": "销售",
        "admin.artworks.saleAll": "销售：全部",
        "admin.artworks.forSale": "在售",
        "admin.artworks.notForSale": "非卖品",
        "admin.artworks.price": "价格",
        "admin.artworks.priceAll": "价格：全部",
        "admin.artworks.priceUnder1k": "< 1,000",
        "admin.artworks.price1kTo5k": "1,000-5,000",
        "admin.artworks.priceAbove5k": "> 5,000",
        "admin.artworks.caseAll": "案例：全部",
        "admin.artworks.hasCase": "有案例",
        "admin.artworks.noCase": "无案例",
        "admin.artworks.none": "当前筛选下没有藏品。",
        "admin.artworks.collectionId": "藏品编号",
        "admin.artworks.uploader": "上传者",
        "admin.artworks.deleteSelected": "删除所选（%@）",
        "admin.artworks.exportSubject": "目录商品导出",
        "admin.artworks.exportMessage": "筛选后的藏品 CSV",
        "admin.artworks.create": "新建藏品",
        "admin.artworks.edit": "编辑藏品",
        "admin.artworks.imported": "已导入 %@ / %@",
        "admin.artworks.unknownError": "未知错误",
        "admin.artworks.deleteTitle": "删除藏品？",
        "admin.artworks.deleteSelectedTitle": "删除所选藏品？",
        "admin.artworks.count": "%@ 件藏品",
        "admin.artworks.official": "官方",
        "admin.artworks.user": "用户",
        "admin.artworks.deleteMessage": "此操作不可撤销。",
        "admin.importReport": "导入报告",
        "admin.summary": "汇总",
        "admin.imported": "导入成功",
        "admin.failed": "失败",
        "admin.failureDetails": "失败详情",
        "admin.importSuccess": "所有行都已成功导入。",
        "admin.batchImport": "批量导入",
        "admin.inputFormat": "输入格式",
        "admin.inputFormat.desc": "每行一件藏品：title|imageUrl|description|price(可选)|collectionId(可选)|currency(可选)|titleZh(可选)|categoryZh(可选)|periodZh(可选)|descriptionZh(可选)|caseId(可选)|salePrice(可选)|saleTime(可选)|salePlatform(可选)|clientRegion(可选)|logisticsCost(可选)|purchaseChannel(可选)|purchaseCost(可选)|riskAdvice(可选)",
        "admin.exampleLine": "示例行...",
        "admin.sharedFields": "共享字段",
        "admin.listingType": "上架类型",
        "admin.category": "分类",
        "admin.period": "年代",
        "admin.validation": "校验",
        "admin.validRows": "有效行：%@",
        "admin.importValidOnly": "仅导入有效行（跳过无效行）",
        "admin.import": "导入",
        "admin.basic": "基础信息",
        "admin.title": "标题",
        "admin.titleZh": "标题（中文）",
        "admin.categoryZh": "分类（中文）",
        "admin.periodZh": "年代（中文）",
        "admin.coverUrl": "封面图 URL",
        "admin.description": "描述",
        "admin.descriptionZh": "描述（中文）",
        "admin.uploadCover": "上传封面",
        "admin.listing": "上架信息",
        "admin.priceField": "价格",
        "admin.currency": "货币",
        "admin.collectionIdField": "藏品编号",
        "admin.autoCollectionId": "自动生成藏品编号",
        "admin.galleryUrls": "图集 URL（每行一个）",
        "admin.uploadGallery": "上传图集图片",
        "admin.caseRecord": "案例记录（可选）",
        "admin.caseId": "案例编号",
        "admin.salePrice": "成交价格",
        "admin.saleTime": "成交时间",
        "admin.salePlatform": "成交平台",
        "admin.clientRegion": "客户地区",
        "admin.logisticsCost": "物流成本",
        "admin.purchaseChannel": "采购渠道",
        "admin.purchaseCost": "采购成本",
        "admin.riskAdvice": "风险建议",
        "admin.uploadingImages": "图片上传中...",
        "admin.save": "保存",
        "admin.validation.titleRequired": "标题不能为空。",
        "admin.validation.categoryRequired": "分类不能为空。",
        "admin.validation.periodRequired": "年代不能为空。",
        "admin.validation.coverUrlInvalid": "封面图必须是有效 URL。",
        "admin.validation.descriptionRequired": "描述不能为空。",
        "admin.validation.collectionRequired": "藏品类型必须填写藏品编号。",
        "admin.validation.collectionFormat": "藏品编号只能使用 a-z、0-9、连字符和下划线。",
        "admin.validation.collectionExists": "藏品编号已存在，请使用唯一值。",
        "admin.validation.pricePositive": "在售藏品的价格必须为正数。",
        "admin.validation.caseSalePrice": "案例记录必须填写成交价格。",
        "admin.validation.caseSaleTime": "案例记录必须填写成交时间。",
        "admin.validation.caseSalePlatform": "案例记录必须填写成交平台。",
        "admin.validation.galleryUrlInvalid": "图集中的所有条目都必须是有效 URL。",
        "admin.error.loadArtworks": "加载藏品失败",
        "admin.error.invalidBaseUrl": "应用基础地址无效。",
        "admin.error.invalidServerResponse": "服务器响应无效。",
        "admin.error.unauthorized": "未授权。",
        "admin.error.requestFailed": "请求失败：%@",
        "admin.error.invalidImage": "图片无效",
        "admin.error.uploadFailed": "上传失败",
        "admin.import.lineFormat": "第 %@ 行：格式应为 title|imageUrl|description 加可选字段。",
        "admin.import.duplicateCollection": "第 %@ 行：本次导入中藏品编号重复。",
        "admin.import.invalidCurrency": "第 %@ 行：货币只能是 USD 或 CNY。",
        "admin.deleteUserResult": "用户已删除",
        "admin.roleUpdated": "角色已更新"
    ]
}

extension NativeArtwork {
    func displayTitle(in language: AppLanguage) -> String {
        if language == .chinese {
            let zh = titleZh?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            return zh.isEmpty ? title : zh
        }
        return title
    }

    func displayCategory(in language: AppLanguage) -> String {
        if language == .chinese {
            let zh = categoryZh?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            if !zh.isEmpty { return zh }
            switch category.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() {
            case "calligraphy":
                return "字画"
            case "misc":
                return "杂项"
            case "porcelain":
                return "瓷器"
            case "jade":
                return "翡翠玉器"
            case "bronze":
                return "铜器"
            default:
                return category
            }
        }
        return category
    }

    func displayPeriod(in language: AppLanguage) -> String {
        if language == .chinese {
            let zh = periodZh?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            if !zh.isEmpty { return zh }
            switch period.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() {
            case "ancient":
                return "古代"
            case "modern":
                return "近现代"
            case "contemporary":
                return "当代"
            case "qing":
                return "清代"
            case "ming":
                return "明代"
            case "song":
                return "宋代"
            case "han":
                return "汉代"
            case "tang":
                return "唐代"
            default:
                return period
            }
        }
        return period
    }
}

extension NativeImageMatch.MatchArtwork {
    func displayTitle(in language: AppLanguage) -> String {
        if language == .chinese {
            let zh = titleZh?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            return zh.isEmpty ? title : zh
        }
        return title
    }

    func displayCategory(in language: AppLanguage) -> String {
        if language == .chinese {
            switch category.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() {
            case "calligraphy":
                return "字画"
            case "misc":
                return "杂项"
            case "porcelain":
                return "瓷器"
            case "jade":
                return "翡翠玉器"
            case "bronze":
                return "铜器"
            default:
                return category
            }
        }
        return category
    }

    func displayPeriod(in language: AppLanguage) -> String {
        if language == .chinese {
            switch period.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() {
            case "ancient":
                return "古代"
            case "modern":
                return "近现代"
            case "contemporary":
                return "当代"
            case "qing":
                return "清代"
            case "ming":
                return "明代"
            case "song":
                return "宋代"
            case "han":
                return "汉代"
            case "tang":
                return "唐代"
            default:
                return period
            }
        }
        return period
    }
}

enum AppErrorPresenter {
    private static var languageManager: LanguageManager { LanguageManager() }

    static func text(_ key: String) -> String {
        languageManager.text(key)
    }

    static func format(_ key: String, _ args: CVarArg...) -> String {
        String(format: text(key), locale: languageManager.language.locale, arguments: args)
    }

    static func message(for error: Error) -> String {
        if let apiError = error as? APIClientError {
            switch apiError {
            case .badURL:
                return text("error.invalidURL")
            case .unauthorized:
                return text("error.unauthorized")
            case .network:
                return text("error.network")
            case .server(let message):
                return message
            }
        }

        if let urlError = error as? URLError {
            switch urlError.code {
            case .timedOut:
                return text("error.timeout")
            case .notConnectedToInternet, .networkConnectionLost, .internationalRoamingOff, .dataNotAllowed:
                return text("error.offline")
            case .userAuthenticationRequired:
                return text("error.authentication")
            case .badURL, .unsupportedURL:
                return text("error.invalidURL")
            case .badServerResponse, .cannotParseResponse:
                return text("error.server")
            default:
                return urlError.localizedDescription
            }
        }

        let nsError = error as NSError
        if nsError.domain == NSURLErrorDomain {
            return message(for: URLError(.init(rawValue: nsError.code)))
        }
        return error.localizedDescription
    }
}
